name: kiwotigo

services:
  caddy:
    image: caddy
    restart: always
    ports:
      - '5432:8080'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - ./:/usr/share/caddy:z

volumes:
  caddy-config:
  caddy-data:
